### PR TITLE
use GitHub actions

### PR DESCRIPTION
**Pull request by jopecko**
addresses https://github.com/typelevel/paiges/issues/304

### CODE REVIEW

**Comment by johnynek** [comment]
This is so great! Thank you so much!

I don't yet see the ci indications here, is that because we don't build PRs from a different repo that change the yaml for security reasons (I guess you could export people's secrets that way).

**Comment by jopecko** [comment]
No problem. I'm no expert but from what I gather from [one of the other ones I did](https://github.com/typelevel/frameless/pull/471#issuecomment-739323139) I put together, the first time it needs to be enabled for the repo and triggered from a local branch.

cc @larsrh

**Comment by jopecko** [comment]
Seems the `tar` command is reporting some errors for missing directories in the `Compress target directories` step: 

```
tar: docs/target: Cannot stat: No such file or directory
tar: core/.js/target: Cannot stat: No such file or directory
tar: .js/target: Cannot stat: No such file or directory
tar: cats/js/target: Cannot stat: No such file or directory
tar: benchmark/target: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
```

This step is generated by the `sbt-github-actions` plugin and I don't currently see a way to customize it. I'll see if I can set aside some time to investigate this further. Sorry for the distraction.

**Comment by larsrh** [comment]
`githubWorkflowArtifactUpload := false` should disable that

**Comment by jopecko** [comment]
@larsrh I was aware of that, however, since the `.travis.yml` file was using the `sbt-ci-release` plugin to publish artifacts and I read the following in the `sbt-github-actions` README:

>Additionally, compiled artifacts are properly uploaded so that jobs which are dependent on build can avoid redundant work (most notably, publish). Thus, publication is guaranteed to be based on binary files that were generated and tested by the build job, rather than re-generated by publish.

I originally had thought it should be left as the default value of `true`. I'll disable it for now but I think the implication is that a `publish` will rebuild the artifacts again. This may be OK for you but just wanted to call that out.

**Comment by johnynek** [comment]
@larsrh your more well versed on this than I am. Looks good to me. Shall we merge?

@jopecko thanks again!

**Pull request merged**
