### PR TITLE
include Native in build aggregation

### PR DESCRIPTION
**Pull request by larsrh**
Blocks #138

### CODE REVIEW

**Comment by larsrh** [comment]
Scaladoc fails here. I could use some help with that.

**Comment by olafurpg** [comment]
Scaladoc fails due to fatal warnings, you can disable fatal warnings for `coreNative` by running `set scalacOptions.in(coreNative, Compile) -= "-Xfatal-warnings"` in the sbt shell.

**Comment by johnynek** [comment]
great! Happy to see the scala-native ecosystem grow.

**Comment by larsrh** [comment]
Let's see whether the build succeeds ☺

**Comment by larsrh** [comment]
That error went away, but now we have a new error: `sbt "++ 2.12.8!" mimaReportBinaryIssues` wants to check bincompat for Scala Native, but no previous artifact exists. Even if I (attempt to) disable that, I get:

```
[error] sbt.librarymanagement.ResolveException: unresolved dependency: org.scala-native#nativelib_native0.3_2.12;0.3.7: not found
[error] unresolved dependency: org.scala-native#javalib_native0.3_2.12;0.3.7: not found
[error] unresolved dependency: org.scala-native#auxlib_native0.3_2.12;0.3.7: not found
[error] unresolved dependency: org.scala-native#scalalib_native0.3_2.12;0.3.7: not found
[error] unresolved dependency: org.scala-native#test-interface_native0.3_2.12;0.3.7: not found
[error] unresolved dependency: org.scalatest#scalatest_native0.3_2.12;3.2.0-SNAP10: not found
[error] unresolved dependency: org.scala-native#nscplugin_2.12.8;0.3.7: not found
```

**Comment by larsrh** [comment]
Problem still happens after this patch:

```diff
diff --git a/build.sbt b/build.sbt
index 9e2b349..79ed9cc 100644
--- a/build.sbt
+++ b/build.sbt
@@ -1,6 +1,5 @@
 import ReleaseTransformations._
 import sbtcrossproject.{crossProject, CrossType}
-import com.typesafe.tools.mima.plugin.MimaPlugin.mimaDefaultSettings
 
 lazy val noPublish = Seq(
   publish := {},
@@ -103,7 +102,7 @@ lazy val paigesSettings = Seq(
     </developers>
   ),
   coverageMinimum := 60,
-  coverageFailOnMinimum := false) ++ mimaDefaultSettings
+  coverageFailOnMinimum := false)
 
 def previousArtifact(version: String, proj: String) = {
   // the "-dbuild..." part is for Scala community build friendliness
@@ -160,17 +159,18 @@ lazy val paigesNative = project
   )
   .aggregate(coreNative)
   .dependsOn(coreNative)
+  .disablePlugins(MimaPlugin)
 
 lazy val core = crossProject(JSPlatform, JVMPlatform, NativePlatform).crossType(CrossType.Pure)
   .in(file("core"))
   .settings(name := "paiges-core")
   .settings(moduleName := "paiges-core")
   .settings(paigesSettings: _*)
-  .settings(mimaPreviousArtifacts := previousArtifact(version.value, "core"))
   .disablePlugins(JmhPlugin)
   .jsSettings(commonJsSettings:_*)
   .jsSettings(coverageEnabled := false)
   .jvmSettings(commonJvmSettings:_*)
+  .jvmSettings(mimaPreviousArtifacts := previousArtifact(version.value, "core"))
   .platformsSettings(JVMPlatform, JSPlatform)(
     libraryDependencies ++= Seq(
       "org.scalatest" %%% "scalatest" % "3.0.6-SNAP5" % Test,
@@ -193,6 +193,11 @@ lazy val core = crossProject(JSPlatform, JVMPlatform, NativePlatform).crossType(
 lazy val coreJVM = core.jvm
 lazy val coreJS = core.js
 lazy val coreNative = core.native
+  .disablePlugins(MimaPlugin)
+  .settings(
+    scalaVersion := Scala211,
+    crossScalaVersions := Seq(Scala211),
+  )
 
 lazy val cats = crossProject(JSPlatform, JVMPlatform).crossType(CrossType.Pure)
   .in(file("cats"))
@@ -203,7 +208,7 @@ lazy val cats = crossProject(JSPlatform, JVMPlatform).crossType(CrossType.Pure)
   .settings(libraryDependencies ++= Seq(
     "org.typelevel" %%% "cats-core" % "1.5.0",
     "org.typelevel" %%% "cats-laws" % "1.5.0" % Test))
-  .settings(mimaPreviousArtifacts := previousArtifact(version.value, "cats"))
+  .jvmSettings(mimaPreviousArtifacts := previousArtifact(version.value, "cats"))
   .disablePlugins(JmhPlugin)
   .jsSettings(commonJsSettings:_*)
   .jsSettings(coverageEnabled := false)
diff --git a/project/plugins.sbt b/project/plugins.sbt
index a9fa5f7..970a01d 100644
--- a/project/plugins.sbt
+++ b/project/plugins.sbt
@@ -1,6 +1,6 @@
 addSbtPlugin("com.github.gseitz"  % "sbt-release"     % "1.0.8")
 addSbtPlugin("com.jsuereth"       % "sbt-pgp"         % "1.1.1")
-addSbtPlugin("com.typesafe"       % "sbt-mima-plugin" % "0.2.0")
+addSbtPlugin("com.typesafe"       % "sbt-mima-plugin" % "0.3.0")
 addSbtPlugin("org.scala-js"       % "sbt-scalajs"     % "0.6.26")
 addSbtPlugin("org.tpolecat"       % "tut-plugin"      % "0.6.4")
 addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"    % "2.3")
```

**Comment by olafurpg** [comment]
@larsrh What happens if you do `.nativeSettings(mimaPreviousArtifacts := Set.empty, ...)`?

**Comment by larsrh** [comment]
Nope, still the same error.

**Comment by johnynek** [comment]
This thread is making me want to renounce all my scala repos...

I really like scala as a language, but we make is WAY too hard to publish libraries.

Maybe it is time for me to investigate mill or fury, or finally build publishing support for bazel.

**Comment by olafurpg** [comment]
@larsrh Whoops, I didn't notice `"++ 2.12.8!"`, the bang `!` overrides `crossScalaVersions := "2.11"` in the Native project, which I suspect causes the resolution errors (it's not related to previous artifacts). The bang is not needed if `crossScalaVersions` is defined for all projects (including `crossScalaVersions := Nil` in the root project).

**Comment by olafurpg** [comment]
@johnynek I feel you, it's totally unreasonable how much time I've spent on publishing...

There are too many different ways to define sbt builds and most styles kinda work until you have a cross-built project with holes in the build matrix and then there's only one way that works reliably in my experience, which is

- define `crossScalaVersions` in all published projects
- remove `project.in(file("."))` and set `crossScalaVersions := Nil` and `skip in publish := true` in the toplevel of build.sbt 
- don't `aggregate`
- `skip in publish := true` for unpublished modules
- only use `++` without the bang

I'm happy to help refactor the paiges build to use that style, it doesn't involve any sbt voodoo (promise)

**Comment by johnynek** [comment]
any build help would be deeply appreciated!

Thank you for the offer @olafurpg (and again, thanks for struggling with this @larsrh )

**Comment by dwijnand** [comment]
Setting `crossScalaVersions := Nil` in the root, aggregating project and using plain `++` (without the bang) should make it work.

**Comment by olafurpg** [comment]
I opened #140 with some build changes.

**Comment by larsrh** [comment]
Closed in favour of #140.

**Pull request closed without merging**
