### PR TITLE
Add dotty build

### PR DESCRIPTION
**Pull request by hugo-vrijswijk**
Adds Scala 3.0.0-M1 as a crossScalaVersion target. I've had to make some minor code changes and upgrade some dependencies to their latest versions.

Still to-do:
- [ ] Have a closer look at compiler options. Warnings are now printed for unknown options because some 2.13 options don't exist in 3.0 anymore
- [ ] Wait for a full Cats release? I've updated Cats to `2.3.0-M2` because that is the only version that supports Scala 3.0.0-M1 but you might want to wait for a stable release

### CODE REVIEW

**Comment by johnynek** [comment]
This is great! When CI is green, I'd love to merge it.

**Comment by hugo-vrijswijk** [comment]
Mima was looking for previous artifacts, which did not exist for Dotty (makes sense). I've now disabled mima for dotty builds

**Review by johnynek — APPROVED** [review]
Thanks for sending this!

Why didn't the js work, BTW?

**Comment by hugo-vrijswijk** [comment]
Thanks for merging! ScalaTest doesn't have a JS Dotty build yet. So while sources compile, tests don't

**Comment by johnynek** [comment]
Since dotty is so early, if it unblocks anyone I'm willing to merge js without tests and publish it.

**Comment by larsrh** [comment]
There is also no Cats build with DottyJS yet.

**Pull request merged**
