### PR TITLE
Refactor build for automatic CI releases

### PR DESCRIPTION
**Pull request by olafurpg**
Builds on top of #139.

- replaces sbt-release with sbt-ci-release so that CI publishes a SNAPSHOT on merge into master (with unique version at every commit) and stable release to Maven Central on tag push. It's possible to disable SNAPSHOT releases if you like, but I personally find them useful to manually validate commits before cutting stable releases.
- introduce `jvm/test` to run tests in all JVM projects.
- refactor build.sbt for (hopefully) easier maintainability and readability.

Important:

Before merging this PR, update four environment variables in the Travis web UI as documented here https://github.com/olafurpg/sbt-ci-release#travis to enable releases from CI. Note that it's possible to generate a custom Sonatype user token to avoid sharing the root password, see https://github.com/olafurpg/sbt-ci-release#optional-create-user-tokens

Notes:

- the old build.sbt and the refactored build.sbt don't report mima errors for v0.2.x. I updated `mimaPreviousArtifact` for v0.2.x to be non-empty but it caused a lot of bincompat errors. I recommend to release v0.3.x and then update build.sbt to enable mima again.
- I tried enabling sbt-tpolecat (https://github.com/DavidGregory084/sbt-tpolecat) which avoids the need for most of the custom `scalacOptions` settings in build.sbt, but it caused a lot of compile errors due to `-Ywarn-unused:params` which is not enabled in the Paiges build. It might be worth looking into the future.

### CODE REVIEW

**Comment by olafurpg** [comment]
I validated that the CI releases work by publishing a SNAPSHOT under com.geirsson with my Paiges fork, see example Travis log https://travis-ci.org/olafurpg/paiges/jobs/513736615

**Comment by olafurpg** [comment]
I updated .travis.yml to run only code coverage for 2.12.8, assuming the coverage is likely similar for 2.11/2.13

**Comment by larsrh** [comment]
I'm willing to give this approach a spin. I'll update the Travis CI variables accordingly and push a new tag.

**Comment by olafurpg** [comment]
Before pushing a new tag, it's good to first validate the SNAPSHOT release works after merge into master.

**Comment by larsrh** [comment]
Thanks for the help, @olafurpg! I've followed the steps for setting up Travis CI; let's see if it works.

**Comment by olafurpg** [comment]
Checking the Travis logs 👀 🍿 🤞 https://travis-ci.org/typelevel/paiges/builds/513761359

**Comment by olafurpg** [comment]
Looks like it worked on the first attempt 💪 

I opened https://github.com/typelevel/paiges/pull/141 with a minor fix for the version number.

**Comment by johnynek** [comment]
This is really wonderful! Thank you.

I guess we need to sign up for scala steward on this repo to automatically bump out sbt plugins and then we may be in good shape.

**Comment by coltfred** [comment]
@johnynek PR created for paiges. https://github.com/fthomas/scala-steward/pull/374

Huge thanks to @olafurpg and @larsrh for being able to get this done.

**Comment by johnynek** [comment]
Thanks @coltfred !

**Pull request merged**
