### PR TITLE
Use custom workflow file for releases

### PR DESCRIPTION
**Pull request by olafurpg**

### CODE REVIEW

**Comment by johnynek** [comment]
I'll try... seems like it can't be more broken. 😅

**Comment by johnynek** [comment]
maybe I shouldn't have merged this...

Aren't there two releases now? The one you added and the previous?

**Comment by larsrh** [comment]
Yeah, everything is completely borked now.

**Comment by olafurpg** [comment]
I didn't run sbt or check the CI after opening this PR. I opened https://github.com/typelevel/paiges/pull/322 to fix the sbt-github-action regression. The "release" job on master may be failing due to Sonatype, which has been having some issues lately.

**Comment by larsrh** [comment]
I am 100% convinced now that the release job is failing because of misconfiguration. We still get the "redirected too many times" error.

**Comment by olafurpg** [comment]
Looks like it, maybe some secrets are missing or are incorrect?

**Pull request merged**
