### PR TITLE
Add me as a maintainer.

### PR DESCRIPTION
**Pull request by coltfred**
Assuming you'll still have me.

### CODE REVIEW

**Comment by johnynek** [comment]
Should we alphabetize by last name (which benefits me), or by first name, which puts Colt in the lead?

**Comment by coltfred** [comment]
I'm fine with whatever order you've used on other projects.

**Comment by johnynek** [comment]
@non any comments?

**Comment by non** [comment]
We should alphabetize by last name and put @coltfred in the middle, IMO.

**Comment by non** [comment]
I've merged this and will reorder the names soon.

**Pull request merged**
