### PR TITLE
Update Scala Native to 0.5.3

### PR DESCRIPTION
**Pull request by ekrich**
Waiting for

- [x] scalatest-funsuite - https://github.com/scalatest/scalatest/pull/2322
- [x] scalatestplus-scalacheck - https://github.com/scalatest/scalatestplus-scalacheck/issues/65
- [x] cats-core - https://github.com/typelevel/cats/issues/4587 requires release https://github.com/typelevel/discipline-munit/pull/288
- [x] discipline-scalatest

### CODE REVIEW

**Comment by ekrich** [comment]
Discipline MUnit has been released now - https://repo1.maven.org/maven2/org/typelevel/discipline-munit_native0.5_3/

**Comment by ekrich** [comment]
Please look at the last commit to make sure I did that correctly.

**Review by TonioGela — APPROVED** [review]
LGTM

**Comment by ekrich** [comment]
Any chance for a release too?

**Pull request merged**
