### PR TITLE
Fix "indent = 2"

### PR DESCRIPTION
**Pull request by ronanM**

### CODE REVIEW

**Comment by non** [comment]
@ronanM So this is a discrepancy between *master* and the release (sorry!). If you try *master* I think the current code works (and doesn't have spaces). Does it work for you?

I'd like to try to release 0.1.1 (with this change), relatively soon. What do you think @johnynek and @coltfred? I can do a release today or this weekend.

**Comment by non** [comment]
The reason I thought this change was important: many of our immediate use cases involve codegen, where the default behavior of `bracketBy` is not the one you want (i.e. you have a delimiter, like parenthesis or braces, and don't necessarily want extra spacing even on the same thing).

**Comment by johnynek** [comment]
I don't want another release without Mima if we can help it. Adding a parameter with a default is not backwards compatible the way scalac compiles it (it totally could be). So I want Mima to avoid any other similar breakage before we publish.

We can just add a method that calls through to the version with more parameters.

As a work around, this is easy to add in user code until then. We should probably document the fundamental operations just to encourage people to think about their own new combinations of those that don't require changing the rendering algorithm.

**Comment by non** [comment]
@johnynek Sure, let's turn on MiMA ASAP.

Since we can't possibly have major downstream dependencies yet, it doesn't seem bad to me to try using this in a few places (e.g. codegen, optparse-applicative, etc) and then release 0.2.0 with (possibly breaking) changes before submitting PRs to other projects to use this.

Feel free to veto if you disagree. It just seems like a bummer to bake-in behavior to `bracketBy` (which is a method things like scalafmt will want) with semantics that won't make sense in many case (i.e. it has the semantics that haskell-wrapping would want, but not parenthesized groups, dot-method application, etc), especially since we know we don't have real users yet.

But I agree that we want MiMA in place before the second release just to figure out what is going on.

**Comment by johnynek** [comment]
Yeah, I'm not saying we should feel locked in, but if it is easy to keep it
compatible I'd like to try and MiMa will let us see when we do break.

bracketBy I just copied from Wadler, but he didn't have lineBreak so he had
no way to express what we probably really want.

**Comment by coltfred** [comment]
MiMa ASAP seems like a good idea, and in general I favor adding more methods than adding ones with default parameters. It can make the scaladoc look a little more verbose, but seems better long term.

**Comment by johnynek** [comment]
see #55

**Comment by coltfred** [comment]
Closing this, since the README uses tightBracketBy.

**Pull request closed without merging**
